# Generated by Django 3.2.4 on 2021-06-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event name:')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
